### ISSUE TITLE
[ROS2 foxy] rosdep

### ISSUE THREAD

**Issue by Thodoris1999** [ros-simulation/gazebo_ros_pkgs#1127]
I am not seeing a rosdep rule for gazebo_ros_pkgsg in foxy. I would create one, but seeing the [eloquent rule](https://github.com/ros/rosdistro/blob/master/eloquent/distribution.yaml#L781), it points to a distro specific branch.
```
gazebo_ros_pkgs:
    doc:
      type: git
      url: https://github.com/ros-simulation/gazebo_ros_pkgs.git
      version: eloquent
    release:
      packages:
      - gazebo_dev
      - gazebo_msgs
      - gazebo_plugins
      - gazebo_ros
      - gazebo_ros_pkgs
      tags:
        release: release/eloquent/{package}/{version}
      url: https://github.com/ros2-gbp/gazebo_ros_pkgs-release.git
      version: 3.4.4-1
    source:
      test_pull_requests: true
      type: git
      url: https://github.com/ros-simulation/gazebo_ros_pkgs.git
      version: eloquent
    status: developed
```
Is there going to be a new branch in this repo for foxy?
