### ISSUE TITLE
IMU Output is unreasonable when my robot is spinning in circle with uniform speed

### ISSUE THREAD

**Issue by KhalidOwlWalid** [ros-simulation/gazebo_ros_pkgs#1363]
### Description
Whenever I am moving my robot in a uniform circular motion, I am getting a negative output for my linear (tangential) acceleration in the negative direction although I believe it should have been zero [Reference : uniform circular motion](https://cnx.org/contents/UYPplaH7@29.32:glPsLbv4@7/Non-uniform-circular-motion)

### Output
```
header:
  stamp:
    sec: 266
    nanosec: 197000000
  frame_id: imu_base_link
orientation:
  x: 2.678757786652316e-07
  y: 4.246988684238048e-07
  z: 0.3740421717030349
  w: 0.9274116959513856
orientation_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
angular_velocity:
  x: 0.0008073019359326919
  y: 0.0005859120509501901
  z: 0.9184899232134838
angular_velocity_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
linear_acceleration:
  x: -2.156493067231797
  y: 10.832547949178531
  z: 9.886436726600044
linear_acceleration_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
---
```
### Expected Output
linear_acceleration.x should have been zero
