### ISSUE TITLE
Problem migrating a pluging to gazebo_ros_pkgs

### ISSUE THREAD

**Issue by piyushk** [ros-simulation/gazebo_ros_pkgs#21]
I have a simple differential drive plugin here based on the original differential drive plugin from the erratic_robot package: https://github.com/utexas-bwi/segbot_simulator/blob/master/segbot_gazebo_plugins/src/diff_drive_plugin.cc

This works as expected with simulator_gazebo-1.7.12 (Gazebo 1.5), but `getWorldPose()` seems to be returning ~0 for position with Gazebo 1.8.6. The position does not change even slightly over time, and the orientation changes somewhat arbitrarily.:

```
pose: 
  pose: 
    position: 
      x: 6.91499350184e-310
      y: 6.91499350199e-310
      z: 0.0
```

On the other hand `/gazebo/get_model/state` seems to be returning the correct value. Since it uses the `getWorldPose` under the hood, I am not sure what the difference is. I am also unsure whether this is an upstream issue or not, but it is something that might be nice to document in gazebo_ros_pkgs migration.
