### ISSUE TITLE
/joint_states keep providing wrong data after robot collision with some object in Gazebo

### ISSUE THREAD

**Issue by jacknlliu** [ros-simulation/gazebo_ros_pkgs#682]
After robot and an object have a collision, and if the `joint trajectory controller` still sends joint positions to the robot, the `/joint_states` will return the wrong data, even if the robot has been moved to another position! And the `joint_trajectory_controller/state` also return wrong data!

` /joint_states` can't return normal data from the current model state!

`/joint_states`:
```yaml
header: 
  seq: 14205682
  stamp: 
    secs: 71085
    nsecs: 101000000
  frame_id: ''
name: ['elbow_joint', 'shoulder_lift_joint', 'shoulder_pan_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
position: [-8.51584976541768, -22393.868370150947, -23210.903847882473, -23059.99195414233, 7.4320796024417355, 9.18637489720941]
velocity: [0.00021875832846863282, 0.00585327683488699, 0.003416905486500389, -0.0001427822974524656, 6.232113829809081e-05, 1.6280227906504893e-06]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
**NOTE:** the joint positions are too large and exceeds the joint limit!

How to fix it? Something related to [gazebo_ros_control](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/kinetic-devel/gazebo_ros_control)? We need the correct joint state to control the robot.

I used Ubuntu 16.04, ROS kinetic, and gazebo7.

https://github.com/ros-controls/ros_controllers/issues/313
